### ISSUE TITLE
No "Apply Entity Framework migrations" Task after installing the Entity Framework Migrations extension

### ISSUE THREAD

**Issue by petelind** [tobania/VSTS.Extension.EntityFrameworkMigrations#1]
Hello Tobania team,
thank you for your solution to the painful problem MS overlooked.
I have successfully installed the extension and was trying to follow approach #2:
This extension contains 2 tasks which should be used in conjunction with each other.
1 during the build phase and the other one during the release phase

Task: Copy Entity Framework migrate.exe during build - DONE, success.
Task: Apply Entity Framework migrations during release - cant do, there is no such task in the list of Tasks.

Can you please advise if its possible that I'm missing something?..
Thank you,
Denis

**Comment by anton-kirschhock** [comment]
Hi there,

Can you share your configuration of both tasks?

**Comment by petelind** [comment]
There is no configuration yet.I just installed the extension to my VS Online organization, added 1st task (copy smigrate into build), and then I cannot perform step 2 - configure how to run migrations (Apply Entity Framework migrations), it is simply missing from the list of the available tasks for the release.I can make screenshots if it will help.Regards,DenisOn Jul 20, 2018 7:20 AM, AntonK <notifications@github.com> wrote:Hi there,
Can you share your configuration of both tasks?

**Comment by GrzegorzDev** [comment]
Hello Tobania team, 

I have the same problem: 
![image](https://user-images.githubusercontent.com/69590938/90027937-5ddc4a80-dcb9-11ea-839c-ab830f72cd0c.png)

Any solution for that?

Best regards
Grzegorz

**Comment by ygeelen-tb** [comment]
@GrzegorzDev @petelind The task "Apply Entity Framework migrations" is only available in Release Definitions, not in Build Definitions. This is mentioned in our documentation.

**Comment by petelind** [comment]
@ygeelen-tb, OK, got it. Thank you!
Can you please share the link on the documentation you mentioned?

**Comment by ygeelen-tb** [comment]
https://marketplace.visualstudio.com/items?itemName=tobania.EntityFrameworkMigrations

https://github.com/tobania/VSTS.Extension.EntityFrameworkMigrations/blob/master/EntityFrameworkMigrations/overview.md
